// <auto-generated/>
global using global::System;
using Crystallography;
using global::System.IO;
using MemoryPack;
using OpenTK.Compute.OpenCL;
using OpenTK.Graphics.ES20;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Reflection.Metadata;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Windows.Forms;
using System.Xml.Linq;
using Tensorflow;
using Tensorflow.Keras;
using Tensorflow.Keras.Callbacks;
using Tensorflow.Keras.Engine;
using Tensorflow.Keras.Layers;
using Tensorflow.NumPy;
using Windows.Media.Devices;
using Windows.UI.Composition;
using xFunc.Maths;
using xFunc.Maths.Expressions;
using xFunc.Maths.Expressions.Programming;
using static Tensorflow.Binding;
using static Tensorflow.KerasApi;
using Crystallography.Controls;
namespace MineraScope
{
    [MemoryPackable]
    public partial struct SimulationProperty
    {
        public string MineralGroupName;
        public string Atoms;
        //public (string Name, double Mol)[]               Atoms1;
        public (string ElementName, double Weight)[][] Atoms1;
        public (string Name, double Mol)[] Atoms2;
        public string DetectorName;
        //　カーボン蒸着厚　（nm）
        public double CarbonCoatThickness;
        // 加速電圧（kV）
        public double BeamEnergy;
        //シミュレーション回数
        public double Count;
        //ステップ
        public double Division;
        //測定時間
        public double LiveTime;
        //照射電流
        public double ProbeCurrent;
        //並列回数
        public int ParallelCount;
        //msaファイル出力先
        public string OutputFolder;
        [MemoryPackIgnore]
        public string[] OutputFiles;
    }



    public partial class GeneratorForm : Form
    {
        public FormMain FormMain;

        private readonly List<EndmemberControl> endmemberControls = [];
        private readonly DeepLearning _deepLearning;
        // 260416Codex: 鉱物 DB の入出力を repository に寄せ、Form の責務を UI 側へ戻していきます。
        private readonly MineralDatabaseRepository _mineralDatabaseRepository;
        // 260416Codex: 学習開始処理を workflow 化し、ボタンイベントから直接 DeepLearning を叩かない形へ寄せます。
        private readonly ModelTrainingWorkflow _modelTrainingWorkflow;
        // 260416Codex: シミュレーション実行計画の組み立てを service 化し、完成 UI へ向けた差し替え点を明確にします。
        private readonly SimulationPlanBuilder _simulationPlanBuilder;
        // 260507Codex: manifest/pool を正本にした不足確認・予約・学習入力作成を担当します。
        private readonly SpectrumPoolWorkflow _spectrumPoolWorkflow;
        // 260416Codex: 計算済み plan の出力と実行を Form から分離し、UI は起動トリガーだけを担当します。
        private readonly SimulationExecutionService _simulationExecutionService;
        // 260511Codex: キャリブレーション画面は閉じても破棄せず、入力値を保持するため 1 インスタンスだけ持ちます。
        private readonly EdxCalibrationForm _edxCalibrationForm;
        // 260507Codex: 下部ドロワーの高さ制御対象を名前検索で保持します。
        private TableLayoutPanel _tableLayoutPanelMain;
        // 260507Codex: 詳細設定とログを差し替えて表示する下部領域です。
        private Panel _panelBottomDrawer;
        // 260507Codex: 詳細設定用の退避パネルは Designer 側の名前を優先して解決します。
        private Control _advancedSettingsContent;
        // 260507Codex: 詳細設定ドロワーも CheckBox で表示状態を表します。
        private CheckBox _checkBoxToggleAdvancedSettings;
        // 260507Codex: 現在ドロワーに表示している内容を記録し、再押下で閉じられるようにします。
        private Control _currentBottomDrawerContent;

        // 260507Codex: 下部ドロワーの標準高さを UI 初期化と開閉処理で共有します。
        private const float BottomDrawerDefaultHeight = 180F;
        // 260508Codex: GeneratorForm の設定ファイル名を保存・復元で共有します。
        private const string UserSettingsFileName = "GeneratorFormSettings.json";

        private string AssemblyPath { get; } = Path.GetDirectoryName(Assembly.GetEntryAssembly()?.Location) ?? AppContext.BaseDirectory;
        // 260416Codex: Python スクリプトはユーザーに見せない固定保存先へ集約します。
        private string PythonScriptOutputPath { get; } = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "MineraScope",
            "PythonScripts");

        // 260430Codex: 親フォーム未接続時の教師データ既定値も Documents 配下の共通パスへそろえます。
        private string DefaultTrainingDataPath => DefaultStoragePaths.TrainingDataFolder;

        // 260424Codex: EDX 出力先は FormMain の共通ファイル設定から参照します。
        private string EdxOutputPath => FormMain?.EdxOutputPath ?? DefaultTrainingDataPath;

        // 260424Codex: DTSA-II パスも FormMain の共通ファイル設定から参照します。
        private string DtsaPath => FormMain?.DtsaPath ?? string.Empty;

        // 260424Codex: モデル保存先は FormMain の共通ファイル設定へ読み書きします。
        private string ModelOutputPath
        {
            get => FormMain?.ModelPath ?? string.Empty;
            set
            {
                if (FormMain is not null)
                {
                    FormMain.ModelPath = value;
                }
            }
        }

        public GeneratorForm()
        {
            InitializeComponent();
            // 260511Codex: EDX キャリブレーション画面を再利用し、フォームを閉じても設定値を失わないようにします。
            _edxCalibrationForm = new EdxCalibrationForm
            {
                Owner = this,
                StartPosition = FormStartPosition.CenterParent,
                Visible = false
            };
            // 260507Codex: 明示リストに入れた生成・EDX・学習設定だけを前回値から復元します。
            LoadUserSettings();
            // 260507Codex: Designer 手作業で追加される新レイアウト部品を実行時に初期化します。
            ConfigureGeneratorLayoutRuntimeState();
            _deepLearning = new(TrainLog);
            // 260416Codex: 既存 helper を Form 初期化時に束ねておき、以降のイベント処理を薄く保ちます。
            _mineralDatabaseRepository = new(AssemblyPath);
            _modelTrainingWorkflow = new(_deepLearning);
            _simulationPlanBuilder = new();
            _spectrumPoolWorkflow = new(new SpectrumPoolRepository(new SpectrumConditionKeyBuilder()), _simulationPlanBuilder);
            // 260416Codex: スクリプト生成と外部実行は専用 service へまとめ、Form から I/O 詳細を隠します。
            _simulationExecutionService = new(new SimulationScriptGenerator());
            // 260416Codex: 固定保存先を事前作成し、設定 UI には表示しないようにします。
            Directory.CreateDirectory(PythonScriptOutputPath);
            // 260416Codex: DB 初期化は repository にまとめ、Form からファイル操作の詳細を外します。
            _mineralDatabaseRepository.EnsureInitialized();
            endmemberControls.AddRange([EndmemberControl1, EndmemberControl2]);
            // 260511Codex: repository へ渡すだけの helper を挟まず、初期表示は直接読み込みます。
            BindMineralSolutions(_mineralDatabaseRepository.Load());

            // 260430Codex: 旧 NumericUpDown の DEBUG 表示切替は対象コントロール廃止後の Designer と合わないため外します。
        }

        // 260507Codex: ログ、組成候補、選択中鉱物詳細を除外して設定値だけを復元します。
        private void LoadUserSettings()
        {
            if (!FormUserSettingsStore.Exists(UserSettingsFileName))
            {
                return;
            }

            var settings = FormUserSettingsStore.Load<GeneratorFormUserSettings>(UserSettingsFileName);
            textBoxDetectorName.Text = settings.DetectorName;
            textBoxModelName.Text = settings.ModelName;
            numericBoxSpectraPerMineral.Value = settings.TargetSpectrumCount;
            numericBoxParallel.Value = settings.ParallelCount;
            numericBoxResolution.Value = settings.Resolution;
            numericBoxEpochs.Value = settings.Epochs;
            numericBoxBatchSize.Value = settings.BatchSize;
            numericBoxEarlyStopping.Value = settings.EarlyStopping;
            numericBoxValidationSplit.Value = settings.ValidationSplit;
            numericBoxProbeCurrent.Value = settings.ProbeCurrent;
            numericBoxLiveTime.Value = settings.LiveTime;
            numericBoxBeamEnergy.Value = settings.BeamEnergy;
            numericBoxCarbonThickness.Value = settings.CarbonThickness;
        }

        // 260507Codex: 次回起動で戻す対象を明示し、CheckedListBox のチェック状態は保存しません。
        internal void SaveUserSettings()
        {
            FormUserSettingsStore.Save(
                UserSettingsFileName,
                new GeneratorFormUserSettings
                {
                    DetectorName = textBoxDetectorName.Text,
                    ModelName = textBoxModelName.Text,
                    TargetSpectrumCount = numericBoxSpectraPerMineral.Value,
                    ParallelCount = numericBoxParallel.Value,
                    Resolution = numericBoxResolution.Value,
                    Epochs = numericBoxEpochs.Value,
                    BatchSize = numericBoxBatchSize.Value,
                    EarlyStopping = numericBoxEarlyStopping.Value,
                    ValidationSplit = numericBoxValidationSplit.Value,
                    ProbeCurrent = numericBoxProbeCurrent.Value,
                    LiveTime = numericBoxLiveTime.Value,
                    BeamEnergy = numericBoxBeamEnergy.Value,
                    CarbonThickness = numericBoxCarbonThickness.Value
                });
        }

        // 260507Codex: Designer を直接編集せず、手作業追加された名前付きコントロールだけを実行時に解決します。
        private void ConfigureGeneratorLayoutRuntimeState()
        {
            _tableLayoutPanelMain = FindFirstExistingControl<TableLayoutPanel>("tableLayoutPanelMain");
            _panelBottomDrawer = FindFirstExistingControl<Panel>("panelBottomDrawer");
            _advancedSettingsContent = FindFirstExistingControl<Control>(
                "panelAdvancedSettings",
                "panelAdvancedSettingsContent",
                "groupBoxTrainModel",
                "groupBoxAdvancedSettings",
                "groupBoxDetailSettings");
            // 260507Codex: 詳細設定はコマンドバー側に置く CheckBox を短い名前でも拾います。
            _checkBoxToggleAdvancedSettings = FindFirstExistingControl<CheckBox>(
                "checkBoxAdvanced",
                "checkBoxDetails",
                "checkBoxToggleAdvancedSettings");

            ConfigureBottomDrawerInitialState();

            buttonRunSpectrumGeneration.Visible = false;
            buttonModelTrain.Text = "モデルを作成";

            HookGeneratorLayoutButtons();
            UpdateAdvancedSettingsButtonText();
        }

        // 260507Codex: 下部ドロワーの初期状態を Designer 側の Row 3 に合わせて閉じた状態へ寄せます。
        private void ConfigureBottomDrawerInitialState()
        {
            if (_panelBottomDrawer is not null)
            {
                _panelBottomDrawer.Visible = false;
                _panelBottomDrawer.AutoScroll = true;
            }

            SetBottomDrawerRowHeight(0F);
        }

        // 260507Codex: Designer 側で追加された詳細設定 CheckBox または旧ボタンに Code Behind の動作だけを接続します。
        private void HookGeneratorLayoutButtons()
        {
            if (_checkBoxToggleAdvancedSettings is not null)
            {
                _checkBoxToggleAdvancedSettings.CheckedChanged -= checkBoxToggleAdvancedSettings_CheckedChanged;
                _checkBoxToggleAdvancedSettings.CheckedChanged += checkBoxToggleAdvancedSettings_CheckedChanged;
            }

            // 260511Codex: Designer 側の Click 接続が残っていても、code-behind 側で表示処理を確実に持ちます。
            buttonCalibration.Click -= buttonCalibration_Click;
            buttonCalibration.Click += buttonCalibration_Click;
        }

        // 260511Codex: キャリブレーション画面は再表示時に既存インスタンスを前面化して値を保持します。
        private void buttonCalibration_Click(object sender, EventArgs e)
        {
            if (_edxCalibrationForm.Visible)
            {
                _edxCalibrationForm.BringToFront();
                return;
            }

            _edxCalibrationForm.Visible = true;
        }

        // 260507Codex: 新 UI の名前候補を再帰検索し、未配置時は null で安全に抜けられるようにします。
        private T FindFirstExistingControl<T>(params string[] names)
            where T : Control
        {
            foreach (var name in names)
            {
                // 260507Codex: Controls.Find の戻り値を型で絞り、最初に見つかった対象だけを返します。
                if (Controls.Find(name, searchAllChildren: true).OfType<T>().FirstOrDefault() is { } control)
                {
                    return control;
                }
            }

            // 260507Codex: auto-generated 扱いの partial なので nullable 注釈ではなく null 許容の実運用に合わせます。
            return null;
        }

        // 260507Codex: 詳細設定 CheckBox のチェック状態を下部ドロワー表示へ同期します。
        private void checkBoxToggleAdvancedSettings_CheckedChanged(object sender, EventArgs e)
        {
            if (sender is not CheckBox checkBox)
            {
                return;
            }

            SetAdvancedSettingsVisible(checkBox.Checked);
        }

        // 260507Codex: 詳細設定ドロワーの表示状態を一か所で切り替えます。
        private void SetAdvancedSettingsVisible(bool visible)
        {
            if (_advancedSettingsContent is null)
            {
                UpdateAdvancedSettingsButtonText();
                return;
            }

            if (visible)
            {
                ShowBottomDrawer(_advancedSettingsContent);
            }
            else if (IsBottomDrawerShowing(_advancedSettingsContent))
            {
                HideBottomDrawer();
            }
            else
            {
                UpdateAdvancedSettingsButtonText();
            }
        }

        // 260507Codex: 下部ドロワーに詳細設定またはログを差し替えて表示します。
        private void ShowBottomDrawer(Control content, float height = BottomDrawerDefaultHeight)
        {
            if (_panelBottomDrawer is null)
            {
                return;
            }

            _panelBottomDrawer.SuspendLayout();
            try
            {
                _panelBottomDrawer.Controls.Clear();
                _panelBottomDrawer.Controls.Add(content);
                content.Dock = DockStyle.Fill;
                content.Visible = true;
                _currentBottomDrawerContent = content;
                _panelBottomDrawer.Visible = true;
                SetBottomDrawerRowHeight(height);
            }
            finally
            {
                _panelBottomDrawer.ResumeLayout(performLayout: true);
            }

            _tableLayoutPanelMain?.PerformLayout();
            UpdateAdvancedSettingsButtonText();
        }

        // 260507Codex: 下部ドロワーを閉じ、TableLayoutPanel の Row 3 を 0px に戻します。
        private void HideBottomDrawer()
        {
            if (_panelBottomDrawer is not null)
            {
                _panelBottomDrawer.Visible = false;
            }

            _currentBottomDrawerContent = null;
            SetBottomDrawerRowHeight(0F);
            _tableLayoutPanelMain?.PerformLayout();
            UpdateAdvancedSettingsButtonText();
        }

        // 260507Codex: RowStyles が Designer 側で未作成の場合も落ちないように高さ変更を保護します。
        private void SetBottomDrawerRowHeight(float height)
        {
            if (_tableLayoutPanelMain is null || _tableLayoutPanelMain.RowStyles.Count <= 3)
            {
                return;
            }

            _tableLayoutPanelMain.RowStyles[3].SizeType = SizeType.Absolute;
            _tableLayoutPanelMain.RowStyles[3].Height = height;
        }

        // 260507Codex: 現在の下部ドロワー内容が指定コンテンツかを開閉ボタンから判定します。
        private bool IsBottomDrawerShowing(Control content) =>
            _panelBottomDrawer is { Visible: true }
            && ReferenceEquals(_currentBottomDrawerContent, content);

        // 260507Codex: 詳細設定ドロワーの表示状態に合わせてボタン文言を更新します。
        private void UpdateAdvancedSettingsButtonText()
        {
            bool advancedVisible = _advancedSettingsContent is not null
                && IsBottomDrawerShowing(_advancedSettingsContent);

            if (_checkBoxToggleAdvancedSettings is not null)
            {
                _checkBoxToggleAdvancedSettings.Text = "詳細設定を表示";
                if (_checkBoxToggleAdvancedSettings.Checked != advancedVisible)
                {
                    _checkBoxToggleAdvancedSettings.Checked = advancedVisible;
                }
            }

        }

        private void BindMineralSolutions(SolidSolution[] solutions, bool clearSelection = true)
        {
            checkedListBoxMinerals.DataSource = null;
            checkedListBoxMinerals.DisplayMember = nameof(SolidSolution.Name);
            checkedListBoxMinerals.DataSource = solutions;

            if (clearSelection)
            {
                checkedListBoxMinerals.ClearSelected();
            }
        }

        private Mineral[] CollectEndmemberMinerals() =>
            endmemberControls
                .Where(comp => !string.IsNullOrWhiteSpace(comp.EndmemberName))
                .Select(comp => new Mineral(comp.EndmemberName, comp.EndmemberFormula))
                .ToArray();

        private string[] ParseConstraints() =>
            textBoxConstraints.Text
                .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Where(constraint => !string.IsNullOrEmpty(constraint))
                .ToArray();

        // 260424Codex: 画面入力の読み取りは partial に逃がさず、フォーム本体で request に変換します。
        private ModelCreationRequest CreateModelCreationRequest() =>
            new(
                // 260424Codex: Python スクリプトの保存先は固定パスへ集約した値を使います。
                new ModelCreationPaths(
                    EdxOutputPath.Trim(),
                    PythonScriptOutputPath,
                    DtsaPath.Trim(),
                    ModelOutputPath.Trim()),
                // 260511Codex: Designer 改名後もモデル保存フォルダ名として画面のモデル名を渡します。
                textBoxModelName.Text.Trim(),
                new SemEdxCondition(
                    textBoxDetectorName.Text.Trim(),
                    numericBoxCarbonThickness.Value,
                    numericBoxBeamEnergy.Value,
                    numericBoxLiveTime.Value,
                    numericBoxProbeCurrent.Value),
                new SimulationExecutionSettings(
                    (int)numericBoxSpectraPerMineral.Value,
                    (double)numericBoxResolution.Value / 100,
                    (int)numericBoxParallel.Value),
                new ModelTrainingSettings(
                    (int)numericBoxEpochs.Value,
                    (int)numericBoxBatchSize.Value,
                    (int)numericBoxEarlyStopping.Value,
                    (float)numericBoxValidationSplit.Value / 100f),
                // 260511Codex: 1 回だけの CheckedListBox helper を避け、選択対象はその場で配列化します。
                checkedListBoxMinerals.CheckedItems.Cast<SolidSolution>().ToArray());

        // 260507Codex: manifest/pool フローに必要な最低限の画面入力を実行前に検証します。
        private static string ValidateModelCreationRequest(ModelCreationRequest request, bool requireDtsaPath)
        {
            if (request.SelectedMineralSolutions.Count == 0)
            {
                return "モデル作成対象の鉱物が選択されていません。";
            }

            if (request.Simulation.TargetSpectrumCount <= 0)
            {
                return "1 鉱物あたりの学習 spectrum 数を 1 以上にしてください。";
            }

            if (request.Simulation.ResolutionStep <= 0)
            {
                return "化学組成分解能を 0 より大きい値にしてください。";
            }

            if (string.IsNullOrWhiteSpace(request.Paths.SpectrumOutputFolder))
            {
                return "スペクトル pool の保存先を指定してください。";
            }

            // 260511Codex: モデル名は保存先の子フォルダ名になるため、空欄と禁止文字を実行前に止めます。
            if (string.IsNullOrWhiteSpace(request.ModelName))
            {
                return "モデル名を入力してください。";
            }

            if (request.ModelName.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0)
            {
                return "モデル名にフォルダ名として使えない文字が含まれています。";
            }

            if (requireDtsaPath && string.IsNullOrWhiteSpace(request.Paths.DtsaFolder))
            {
                return "DTSA-II のフォルダを指定してください。";
            }

            return string.Empty;
        }

        // 260416Codex: シミュレーション実行の重複を helper 利用に寄せて簡素化
        private async void buttonRunSpectrumGeneration_Click(object sender, EventArgs e)
        {
            var request = CreateModelCreationRequest();
            string validationMessage = ValidateModelCreationRequest(request, requireDtsaPath: true);
            if (!string.IsNullOrEmpty(validationMessage))
            {
                MessageBox.Show(validationMessage, "エラー", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            // 260507Codex: manifest の Completed 不足分だけを予約し、予約済み spectrum から実行 plan を作ります。
            var plan = _spectrumPoolWorkflow.CreateMissingSimulationPlan(request, out var shortages);
            if (plan.Batches.Count == 0)
            {
                string message = shortages.Count == 0
                    ? "不足している spectrum はありません。"
                    : SpectrumPoolWorkflow.FormatShortageMessage(shortages);
                MessageBox.Show(message, "スペクトル生成", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            buttonRunSpectrumGeneration.Enabled = false;
            try
            {
                // 260507Codex: 実行結果を受け取り、生成成功/失敗を manifest の status へ反映します。
                var results = await _simulationExecutionService.RunAsync(plan);
                _spectrumPoolWorkflow.ApplySimulationResults(results);
            }
            finally
            {
                buttonRunSpectrumGeneration.Enabled = true;
            }

            var remainingShortages = _spectrumPoolWorkflow.GetShortages(request);
            if (remainingShortages.Count > 0)
            {
                MessageBox.Show(
                    SpectrumPoolWorkflow.FormatShortageMessage(remainingShortages),
                    "スペクトル生成",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information);
            }
            else
            {
                buttonRunSpectrumGeneration.Visible = false;
                MessageBox.Show("必要な spectrum pool がそろいました。", "スペクトル生成", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }
        #region EndmemberControl
        // EndmemberControlに端成分の情報を設定
        // 端成分数に応じてコントロールを追加/削除      
        // 260416Codex: 選択済み固溶体の表示準備を共通化
        private void ResetVisibleEndmemberControls()
        {
            foreach (var control in endmemberControls)
            {
                control.Reset();
                control.Visible = false;
                control.Enabled = true;
            }
        }

        // 260416Codex: 既定で表示する端成分コントロール数を明示
        private void ShowDefaultEndmemberControls()
        {
            for (int i = 0; i < Math.Min(2, endmemberControls.Count); i++)
            {
                endmemberControls[i].Visible = true;
            }
        }

        // 260416Codex: 動的に追加した端成分コントロールの破棄処理を分離
        private void RemoveDynamicEndmemberControls()
        {
            for (int i = endmemberControls.Count - 1; i >= 2; i--)
            {
                var ctrl = endmemberControls[i];
                endmemberControls.Remove(ctrl);
                ctrl.Dispose();
            }
        }

        // 260416Codex: 必要数まで EndmemberControl を増やす
        private void EnsureEndmemberControlCount(int requiredCount)
        {
            while (endmemberControls.Count < requiredCount)
            {
                AddNewEndmemberControl();
            }
        }

        // 260416Codex: 端成分の UI 反映を1か所に集約
        private static void ApplyMember(EndmemberControl control, Mineral member)
        {
            control.EndmemberName = member.Name;
            control.EndmemberFormula = member.FormulaText;
            control.Enabled = true;
            control.Visible = true;
        }

        // 260416Codex: 端成分 UI 更新の分岐を早期 return ベースに整理
        private void UpdateEndmemberUI()
        {
            if (checkedListBoxMinerals.SelectedItem is not SolidSolution selectedSolution)
            {
                // 260416Codex: 未選択時の初期表示を helper で統一
                ResetVisibleEndmemberControls();
                ShowDefaultEndmemberControls();
                return;
            }

            // 260416Codex: 選択済み固溶体に切り替わる前に余分なコントロールを整理
            RemoveDynamicEndmemberControls();
            ResetVisibleEndmemberControls();
            var members = selectedSolution.Members;

            if (members is null)
            {
                // 260416Codex: メンバー未設定時も既定表示に寄せる
                ShowDefaultEndmemberControls();
                return;
            }

            if (members.Length == 1)
            {
                // 260416Codex: 単一端成分時の表示設定を最短経路にする
                ApplyMember(EndmemberControl1, members[0]);
                EndmemberControl2.Enabled = true;
                EndmemberControl2.Visible = true;
                return;
            }

            // 260416Codex: 必要数を確保してから順番に反映する
            EnsureEndmemberControlCount(members.Length);
            for (int i = 0; i < members.Length; i++)
            {
                ApplyMember(endmemberControls[i], members[i]);
            }
        }
        // 新しいEndmemberコントロールを追加
        private void AddNewEndmemberControl()
        {
            // 260511Codex: FlowLayoutPanel が配置するため、追加行は既存行のサイズだけ合わせます。
            var newComp = new EndmemberControl
            {
                Size = endmemberControls[^1].Size
            };

            flowLayoutPanelEndmembers.Controls.Add(newComp);
            endmemberControls.Add(newComp);
        }
        #endregion
        #region 選択されている鉱物の条件式、化学組成リストを更新・表示
        private void UpdateSelectedSolution()
        {
            // 260511Codex: 未選択時は guard clause で詳細欄を空に戻します。
            if (checkedListBoxMinerals.SelectedItem is not SolidSolution selectedSolution)
            {
                textBoxConstraints.Text = "";
                textBoxCompositionList.Text = "";
                textBoxMineralName.Text = "";
                textBoxMemo.Text = "";
                return;
            }
            textBoxMineralName.Text = selectedSolution.Name;
            textBoxMemo.Text = selectedSolution.Formula;

            // 条件式を表示
            textBoxConstraints.Text = selectedSolution.Constraints.Length > 0
                ? string.Join($",{Environment.NewLine}", selectedSolution.Constraints)
                : string.Empty;
            // 化学組成リストを表示
            double resolution = (double)numericBoxResolution.Value / 100;
            // 260507Codex: target は学習件数なので、組成リスト表示は分解能からの全候補を使います。
            var compositions = selectedSolution.EnumerateCandidateFractions(resolution);

            // 分割できなかった場合（resolution=0など）
            if (compositions.Length == 0)
            {
                textBoxCompositionList.Text = "計算できません";
            }
            else
            {
                textBoxCompositionList.Text = string.Join(
                    Environment.NewLine,
                    compositions.Take(200).Select(ratio => FormatFractionMap(selectedSolution, ratio)));
            }
        }
        #endregion
        // 260507Codex: 組成候補表示は端成分名と比率だけにし、ファイル名生成ルールから切り離します。
        private static string FormatFractionMap(SolidSolution solution, double[] fractions) =>
            string.Join(
                ", ",
                solution.Members.Select((member, index) =>
                    $"{member.Name}: {(index < fractions.Length ? fractions[index] : 0):F3}"));

        #region EndmemberControlの追加と削除
        private void buttonEndmemberAdd_Click(object sender, EventArgs e)
        {
            AddNewEndmemberControl();
        }

        private void buttonEndmemberDelete_Click(object sender, EventArgs e)
        {
            if (endmemberControls.Count <= 1)
            {
                return;
            }

            var lastControl = endmemberControls.Last();

            endmemberControls.Remove(lastControl);
            // メモリ解放
            lastControl.Dispose();
        }
        #endregion

        // 260416Codex: 追加・更新で共通の固溶体生成処理をまとめる
        private bool TryCreateSolutionFromInputs(out SolidSolution solution)
        {
            var members = CollectEndmemberMinerals();
            if (members.Length == 0)
            {
                solution = null!;
                return false;
            }

            solution = new SolidSolution(
                textBoxMineralName.Text.Trim(),
                textBoxMemo.Text.Trim(),
                members,
                ParseConstraints());
            return true;
        }

        // 260511Codex: 保存と再バインドはここに寄せ、薄い保存 helper は挟みません。
        private void SaveAndBindSolutions(SolidSolution[] solutions, bool clearSelection = true)
        {
            _mineralDatabaseRepository.Save(solutions);
            BindMineralSolutions(solutions, clearSelection);
        }

        // 260416Codex: ItemCheck 後の再計算をメソッドグループで簡潔にする
        private void checkedListBoxMinerals_ItemCheck(object sender, ItemCheckEventArgs e)
        {
            // 260511Codex: ItemCheck 反映後に、選択中鉱物の候補表示だけを遅延更新します。
            BeginInvoke(new Action(UpdateSelectedSolution));
        }

        private void checkedListBoxMinerals_SelectedIndexChanged(object sender, EventArgs e)
        {
            UpdateEndmemberUI();
            UpdateSelectedSolution();
        }

        #region リストに追加・更新・削除・初期化メソッド
        #region 追加メソッド
        // 260416Codex: 追加時の入力変換を helper ベースに統一
        private void buttonAddMineral_Click(object sender, EventArgs e)
        {
            // 260416Codex: 入力からの固溶体生成を helper に統一
            if (!TryCreateSolutionFromInputs(out var newSolution))
                return;

            // 260416Codex: 保存と再バインドは共通 helper に寄せ、追加処理の本筋だけを残します。
            SaveAndBindSolutions(
                _mineralDatabaseRepository.Load()
                .Append(newSolution)
                .ToArray(),
                clearSelection: false);
        }
        #endregion
        #region 更新メソッド
        // 260416Codex: 更新時の入力変換も追加処理と揃える
        private void buttonUpdateMineral_Click(object sender, EventArgs e)
        {
            int selectedIndex = checkedListBoxMinerals.SelectedIndex;
            // 260416Codex: 更新時も追加時と同じ入力変換を使う
            if (!TryCreateSolutionFromInputs(out var updatedSolution))
                return;

            // 260511Codex: 更新対象の配列も repository から直接読みます。
            var existingSolutions = _mineralDatabaseRepository.Load();
            existingSolutions[selectedIndex] = updatedSolution;

            // 260416Codex: 更新後の永続化と再表示も共通 helper へ寄せます。
            SaveAndBindSolutions(existingSolutions);
        }
        #endregion
        #region 削除メソッド
        // 260416Codex: 削除後の保存と再バインドも共通 helper を使って読みやすくします。
        private void buttonDeleteMineral_Click(object sender, EventArgs e)
        {
            int selectedIndex = checkedListBoxMinerals.SelectedIndex;
            SaveAndBindSolutions(
                _mineralDatabaseRepository.Load()
                .Where((_, index) => index != selectedIndex)
                .ToArray());
        }
        //全削除メソッド
        private void buttonDeleteAllMinerals_Click(object sender, EventArgs e)
        {
            // 260416Codex: 全削除時も共通 helper を通し、一覧クリアの手順を統一します。
            SaveAndBindSolutions([]);
        }
        #endregion
        #region 初期化メソッド
        private void buttonResetMinerals_Click(object sender, EventArgs e)
        {
            // 260416Codex: DB 初期化のファイル操作は repository に閉じ込めます。
            _mineralDatabaseRepository.Reset();
            // 260416Codex: Reset 後は再保存せず、読み直した内容をそのまま再表示します。
            BindMineralSolutions(_mineralDatabaseRepository.Load());
        }
        #endregion
        #endregion
        private void TrainLog(string message)
            => TextBoxLogHelper.AppendLine(textBoxModelLog, message);
        //分類モデル
        private async void buttonModelTrain_Click(object sender, EventArgs e)
        {
            // 260416Codex: 学習開始も request -> plan -> workflow の流れに揃え、今後の統合実行へつなげます。
            var request = CreateModelCreationRequest();
            string requestValidationMessage = ValidateModelCreationRequest(request, requireDtsaPath: false);
            if (!string.IsNullOrEmpty(requestValidationMessage))
            {
                MessageBox.Show(requestValidationMessage, "エラー", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            // 260507Codex: 学習前に pool manifest の Completed 件数を確認し、不足があれば学習へ進みません。
            var trainingPools = _spectrumPoolWorkflow.CreateTrainingPools(request, out var shortages);
            if (shortages.Count > 0)
            {
                buttonRunSpectrumGeneration.Visible = true;
                MessageBox.Show(
                    SpectrumPoolWorkflow.FormatShortageMessage(shortages),
                    "スペクトル不足",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Information);
                return;
            }

            var trainingPlan = _modelTrainingWorkflow.CreatePlan(request, trainingPools);
            var validationMessage = _modelTrainingWorkflow.Validate(trainingPlan);
            if (validationMessage is not null)
            {
                MessageBox.Show(validationMessage, "エラー", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            // 260511Codex: FormMain にはモデル群の親フォルダを保持し、個別モデル名フォルダは comboBox 側で選ばせます。
            ModelOutputPath = string.IsNullOrWhiteSpace(request.Paths.ModelOutputFolder)
                ? DefaultStoragePaths.ModelsFolder
                : request.Paths.ModelOutputFolder;
            buttonRunSpectrumGeneration.Visible = false;

            // 260511Codex: 訓練ログは現在の配置に残したまま、実行前に内容だけをクリアします。
            buttonModelTrain.Enabled = false;
            textBoxModelLog.Clear();

            try
            {
                // 260416Codex: 実際の学習本体は workflow に移し、Form は UI 状態管理だけを担当します。
                await _modelTrainingWorkflow.RunAsync(trainingPlan);
                // 260511Codex: 新しく作成したモデル名フォルダを FormMain のモデル選択欄へ即時反映します。
                FormMain?.RefreshModelPathList(request.ModelName);
            }
            finally
            {
                buttonModelTrain.Enabled = true;
            }
        }

        private void buttonToggleAllMinerals_Click(object sender, EventArgs e)
        {
            // 260511Codex: 同じ CheckedListBox への繰り返し参照をローカルにまとめます。
            var mineralsList = checkedListBoxMinerals;
            if (mineralsList.Items.Count == 0)
            {
                return;
            }

            // 260511Codex: 1 箇所だけの helper にせず、一括チェック処理をイベント内で完結させます。
            bool newState = mineralsList.CheckedItems.Count != mineralsList.Items.Count;
            mineralsList.BeginUpdate();
            try
            {
                for (int i = 0; i < mineralsList.Items.Count; i++)
                {
                    mineralsList.SetItemChecked(i, newState);
                }
            }
            finally
            {
                mineralsList.EndUpdate();
            }
        }

        private void GeneratorForm_FormClosing(object sender, FormClosingEventArgs e)
        {
            // 260507Codex: 非表示にする前に、明示リストの設定値だけを保存します。
            SaveUserSettings();
            // 260511Codex: 親を隠すときは子のキャリブレーション画面も破棄せず一緒に隠します。
            _edxCalibrationForm.Visible = false;
            // 260416Codex: 閉じる操作は破棄せず非表示にするだけなので未使用のローカルを削除します。
            e.Cancel = true;
            Visible = false;
        }
    }
}
